services:
  - type: web
    name: file-upload-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: DATABASE_URL
        fromDatabase:
          name: file-upload-db
          property: connectionString

databases:
  - name: file-upload-db
    databaseName: fileupload
    user: fileupload_user
